Dev
VictorYarosh/weather pull request #1
Opened 2022-09-21 10:57 UTC by VictorYarosh

2022-09-22 07:22 UTC, sergt-bilberrry commented on src/components/CardsWeather.tsx
>  `;
Please, keep it simple.
Do not nest tags where they are not needed.
Need to divide it down into three additional components.
Example: 
`const TitleWrapper = styled.div.....`
`const Title = styled.p.....`
`const TitleSub = styled.span.....`

2022-09-22 07:23 UTC, sergt-bilberrry commented on src/components/CardsWeather.tsx
>  `;
The same with dividing. Please check all your styles

2022-09-22 07:25 UTC, sergt-bilberrry commented on src/components/CardsWeather.tsx
>    const dateBuilder = (d: Date) => {
Please move it to a separate function, to some **utils.ts** file.

2022-09-22 07:26 UTC, sergt-bilberrry commented on src/components/CardsWeather.tsx
>  };
Please move all constants to the const.ts file. And check the rest files.

2022-09-22 07:39 UTC, sergt-bilberrry requested changes
Please fix the comments.

2022-09-22 09:37 UTC, sergt-bilberrry commented
Also, move all logic from weather components to the use-weather.ts hook, and place it near the main component file.

2022-09-22 12:49 UTC, VictorYarosh commented on src/components/CardsWeather.tsx
>  `;
Im fix this.

2022-09-22 12:49 UTC, VictorYarosh commented on src/components/CardsWeather.tsx
>  `;
this to

2022-09-22 20:55 UTC, VictorYarosh commented on src/components/CardsWeather.tsx
>  };
this done

2022-09-24 19:29 UTC, VictorYarosh commented on src/components/CardsWeather.tsx
>    const dateBuilder = (d: Date) => {
all fix

2022-09-26 06:37 UTC, sergt-bilberrry commented
Please use one file naming style don't mix.
Example: 
cards-weather.styled.tsx
cards-weather.tsx

or: 
CardsWeather.styled.tsx
CardsWeather.tsx

2022-09-26 06:40 UTC, sergt-bilberrry commented
Please use the right naming for styled files.
Before `styled`, add a dot not a minus
`cards-weather.styled.tsx`

2022-09-26 06:53 UTC, sergt-bilberrry commented on src/App.tsx
>  const BodyTitle = styled.div`
Wtf ?
1. What are styles doing here? (move it to some general styled file. Maybe cocommon.styled.tsx)
2. What is this component mean? Why it has the name "BodyTitle" but you wrap weather cards?

2022-09-26 06:57 UTC, sergt-bilberrry commented on src/components/cards/CardsWeather.tsx
> +const CardsWeather = () => {
You have a problem with naming. Why did you name it like you have many but below only one card?

2022-09-26 06:58 UTC, sergt-bilberrry commented on src/components/cards/CardsWeather.tsx
> +      </Dropdown>
please move it to a separate component

2022-09-26 07:00 UTC, sergt-bilberrry commented on src/components/cards/cards-weather-all-styled.tsx
> +`;
This is a duplicate code from cards-weather styled. Please remove it and reuse it.

2022-09-26 07:00 UTC, sergt-bilberrry commented on src/components/navbar/Navbar.tsx
> +
wtf ?

2022-09-26 07:01 UTC, sergt-bilberrry commented on src/components/navbar/Navbar.tsx
> +  const [tasks, setTasks] = useState<Task[]>([]);
wtf?

2022-09-26 07:02 UTC, sergt-bilberrry commented on src/components/navbar/Navbar.tsx
> +      </Links>
I think you should move it to a separate component `Logo`.

2022-09-26 07:05 UTC, sergt-bilberrry commented on src/components/navbar/Navbar.tsx
> +      </Links>
Wtf? 
You have a very strange structure )))
```
Links = a
LinksPage = div
```
it will be 
`<a> <div> GitHub </div><div> About </div></a>`

Please fix it and change it to a list with items.

2022-09-26 07:07 UTC, sergt-bilberrry commented
Please don't make unnecessary duplicates with file names.
example:
`navbar/Navbar.tsx`

change to 
`navbar/index.tsx`

2022-09-26 07:10 UTC, sergt-bilberrry commented
Please use the same name styling everywhere.
example: 
`src/components/navbar/styled.tsx` styled file name without component name.
or
`src/components/cards/cards-weather.styled.tsx` styled file name with component name.

2022-09-26 07:12 UTC, sergt-bilberrry commented on src/hooks/use-weather.tsx
> +    };
move it to utils.ts
Think about reusing. + months/days move to const.ts file

2022-09-26 07:14 UTC, sergt-bilberrry commented on src/hooks/use-weather.tsx
> +        weather: [{ main: null, description: null }],
please move this object to the const.ts file. And change NaN to null.

2022-09-26 07:16 UTC, sergt-bilberrry commented on src/hooks/use-weather.tsx
> +const useFetch = (s: string) => {
wtf is `s`?

2022-09-26 07:21 UTC, sergt-bilberrry commented on src/components/cards/CardsWeather.tsx
> +  const {dateBuilder,data,isLoading} = useFetch(`${api.base}weather?q=Kyiv,ua&units=metric&APPID=${api.key}`);
you use hook name doesn't explain to me what it will do. Please rename it to a more specific name (good practice to have the same name as you name a hook file) and move it to the component where we use it.
Because we don't reuse it and have specific logic for only the weather component.

2022-09-26 07:21 UTC, sergt-bilberrry commented on src/hooks/use-weather.tsx
> +    useEffect(() => {
async

2022-09-26 07:22 UTC, sergt-bilberrry commented on src/hooks/use-weather.tsx
> +        fetch(`${api.base}weather?q=Kyiv,ua&units=metric&APPID=${api.key}`)
await + try / catch
Please read some information on google with an example.
async/await + try / catch + fetch

2022-09-26 07:24 UTC, sergt-bilberrry commented on src/hooks/use-weather.tsx
> +                setLoading(false);
if your request failed you receive an infinite loading. Because you set loading to false only when having a success request.

2022-09-26 07:26 UTC, sergt-bilberrry commented
remove all .css files in the project. If you need global styles like body use helpers from styled-component
https://styled-components.com/docs/api#createglobalstyle

2022-09-26 12:00 UTC, VictorYarosh commented on src/components/cards/CardsWeather.tsx
> +      </Dropdown>
fix

2022-09-26 12:02 UTC, VictorYarosh commented on src/components/cards/cards-weather-all-styled.tsx
> +`;
remove

2022-09-26 12:07 UTC, VictorYarosh commented on src/components/navbar/Navbar.tsx
> +      </Links>
fix

2022-09-26 12:11 UTC, VictorYarosh commented on src/components/navbar/Navbar.tsx
> +      </Links>
ready

2022-09-26 12:22 UTC, VictorYarosh commented on src/hooks/use-weather.tsx
> +    };
I spread it through the files

2022-09-27 13:02 UTC, VictorYarosh commented on src/hooks/use-weather.tsx
> +const useFetch = (s: string) => {
i fix

2022-09-27 13:17 UTC, VictorYarosh commented on src/hooks/use-weather.tsx
> +        weather: [{ main: null, description: null }],
I don't know why, but I did it))

2022-09-27 13:22 UTC, VictorYarosh commented on src/components/cards/CardsWeather.tsx
> +  const {dateBuilder,data,isLoading} = useFetch(`${api.base}weather?q=Kyiv,ua&units=metric&APPID=${api.key}`);
this fix

2022-09-29 11:13 UTC, VictorYarosh commented on src/hooks/use-weather.tsx
> +    useEffect(() => {
ready

2022-09-29 20:12 UTC, sergt-bilberrry commented on package.json
>      "@types/react-router-dom": "^5.3.3",
Please move all @types to devDepencies

2022-09-29 20:13 UTC, sergt-bilberrry commented on package.json
>      "@types/react-router-dom": "^5.3.3",
@testing-.... also to the devDepencies section

2022-09-29 20:21 UTC, sergt-bilberrry commented on .eslintrc
> +    "plugin:@typescript-eslint/recommended"
you forgot to extend the typescript plugin, add after line #10:
`"plugin:prettier/recommended"`

and fix all Eslint issues.

2022-09-29 20:22 UTC, sergt-bilberrry commented on src/App.tsx
> +      <Title>
What is the **Title** component do and why does it have a strange name?

2022-09-29 20:26 UTC, sergt-bilberrry commented on src/components/cards/cards-weather.styled.tsx
> +`;
wtf? Please move it.

2022-09-29 20:31 UTC, sergt-bilberrry commented on src/components/cards/cards-weather.tsx
> +const CartWeather = () => {
You are inattentive. Wtf is Cart? Please make a decision what are you want Cart or a Card? ))
Please fix all files.

2022-09-29 20:32 UTC, sergt-bilberrry commented on src/components/cards/cards-weather.tsx
> +  const {dateBuilder,isLoading,data,error} = useCartWeather(`${api.base}weather?q=Kyiv,ua&units=metric&APPID=${api.key}`);
Why you passed the link but don't use it in the hook?
I think you need to remove it here.

2022-09-29 20:33 UTC, sergt-bilberrry commented on src/components/cards/cards-weather.tsx
> +  if (error) console.log(error)
remove it, and use try/catch with axios. Please read more about that.

2022-09-29 20:35 UTC, sergt-bilberrry commented on src/components/cards/commons/dropdown.tsx
> +import React from "react";
move it to the first line.

2022-09-29 20:36 UTC, sergt-bilberrry commented on src/components/navbar/logo.tsx
> +import React from "react";
the same

2022-09-29 20:37 UTC, sergt-bilberrry commented on src/components/navbar/logo.tsx
> +        <Links>
Links? O.o
What does it do there?

2022-09-29 20:38 UTC, sergt-bilberrry commented on src/components/navbar/logo.tsx
> +            <LogoTxt>Weather by VicBox</LogoTxt>
the same.
Please move it to the separate styles and the separate component with a folder.
**logo**

2022-09-29 20:41 UTC, sergt-bilberrry commented on src/components/navbar/navbar.tsx
> +import React from "react";
rename file. to the `index.tsx`
try don't use the same name.
Because it will generate the path:
`./components/navbar/navbar";` <- duplicate name

instead of:
`./components/navbar";`

2022-09-29 20:42 UTC, sergt-bilberrry commented on src/const.ts
> +}
move it to the weather component const.ts file.

2022-09-29 20:42 UTC, sergt-bilberrry commented on src/hooks/useCartWeather.tsx
> +import axios from 'axios';
to the top.

2022-09-29 20:43 UTC, sergt-bilberrry commented on src/hooks/useCartWeather.tsx
> +const useCartWeather = (url: string) => {
1. Fix name.
2. Do something with `url` property.

2022-09-29 20:44 UTC, sergt-bilberrry commented on src/hooks/useCartWeather.tsx
> +  const [error, setError] = useState(null);
redundant, remove it.

2022-09-29 20:45 UTC, sergt-bilberrry commented on src/hooks/useCartWeather.tsx
> +      });
use async/await + try/catch

2022-09-29 20:47 UTC, sergt-bilberrry commented
`useCartWeather.ts
`
Please use one file naming style don't mix.
Example:
cards-weather.styled.tsx
cards-weather.tsx

or:
CardsWeather.styled.tsx
CardsWeather.tsx

2022-09-29 20:48 UTC, sergt-bilberrry commented
`index.css
`
remove all .css files in the project. If you need global styles like body use helpers from styled-component
https://styled-components.com/docs/api#createglobalstyle

2022-09-29 20:50 UTC, sergt-bilberrry requested changes
Please fix comments. And be more attentive.
Some comments I already write twice

2022-09-30 07:18 UTC, VictorYarosh commented on package.json
>      "@types/react-router-dom": "^5.3.3",
fix

2022-09-30 08:08 UTC, VictorYarosh commented on src/components/navbar/logo.tsx
> +        <Links>
I was reusing a component

2022-09-30 12:12 UTC, sergt-bilberrry commented on src/hooks/useCardWeather.tsx
> +    getWeather().then((r) => null);
wtf?

2022-09-30 12:12 UTC, sergt-bilberrry commented on src/hooks/useCardWeather.tsx
> +    async function getWeather() {
please use arrow function

2022-09-30 12:13 UTC, sergt-bilberrry commented on src/hooks/useCardWeather.tsx
> +      } catch (isLoading) {
oO wtf?
catch (error) {
console.error(error);
setLoading(false);
}

2022-09-30 12:32 UTC, VictorYarosh commented on src/hooks/useCardWeather.tsx
> +    async function getWeather() {
fix

2022-09-30 12:32 UTC, VictorYarosh commented on src/hooks/useCardWeather.tsx
> +    getWeather().then((r) => null);
its eslint fix this

2022-09-30 13:41 UTC, sergt-bilberrry commented on src/App.tsx
> +      <Index />
wtf?

2022-09-30 13:41 UTC, sergt-bilberrry commented on src/App.tsx
> +      <CardsTitle>
wtf?

2022-09-30 13:43 UTC, sergt-bilberrry commented
`dropdown-styled.ts 
`rename it

2022-09-30 13:45 UTC, sergt-bilberrry commented on src/components/cards/const.ts
> +};
I already said, move it to weather component to const.ts

2022-09-30 13:45 UTC, sergt-bilberrry commented on src/components/logo/logo-styled.tsx
> +export const LogoTxt = styled.a`
Txt? Wft ?

2022-09-30 13:46 UTC, sergt-bilberrry commented on src/components/logo/logo-styled.tsx
> +export const LinksImg = styled.img`
Wtf LinksImg?

2022-09-30 13:46 UTC, sergt-bilberrry commented on src/components/logo/logo.tsx
> +    </Links>
!!!!!!!!

2022-09-30 13:47 UTC, sergt-bilberrry commented
`useCardWeather.tsx`
rename it!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2022-09-30 13:54 UTC, sergt-bilberrry commented on src/hooks/useCardWeather.tsx
> +    getWeather().then((r) => null);
getWeather().catch((error) => {
      console.error(error);
    });

2022-09-30 13:55 UTC, sergt-bilberrry requested changes
Please fix comments

2022-09-30 17:33 UTC, VictorYarosh commented on src/App.tsx
> +      <Index />
done

2022-09-30 17:34 UTC, VictorYarosh commented on src/App.tsx
> +      <CardsTitle>
done

2022-09-30 17:36 UTC, VictorYarosh commented on src/components/cards/commons/dropdown-styled.ts
> +export const BurgerContentText = styled.a`
done

2022-09-30 17:42 UTC, VictorYarosh commented on src/components/logo/logo-styled.tsx
> +export const LogoTxt = styled.a`
rename on LogoName done

2022-09-30 17:43 UTC, VictorYarosh commented on src/components/logo/logo-styled.tsx
> +export const LinksImg = styled.img`
rename on LogoImg

2022-09-30 17:47 UTC, VictorYarosh commented on src/hooks/useCardWeather.tsx
> +    getWeather().then((r) => null);
done

2022-09-30 18:26 UTC, VictorYarosh commented on src/components/logo/logo.tsx
> +    </Links>
done

2022-09-30 18:54 UTC, VictorYarosh commented on src/components/cards/const.ts
> +};
done

2022-10-05 12:46 UTC, toserg commented on src/components/containers/layout.tsx
> +    <CardWeather />
What is it doing here? It will be on all your pages. Did you really need that?

2022-10-05 12:47 UTC, toserg commented on src/components/containers/types.ts
> +// }
Please remove commented code.

2022-10-05 12:49 UTC, toserg commented on src/components/ui/navbar/navbar.styled.tsx
> +  @media (max-width: 425px) {
add the empty line.

2022-10-05 12:49 UTC, toserg commented on src/components/ui/navbar/navbar.styled.tsx
> +  @media (max-width: 425px) {
`list-style: none;

  @media (max-width: 425px) {`

2022-10-05 12:51 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +const CardWeather = () => {
Rename it to "WeatherCard" because your folder and the rest files have that name.

2022-10-05 12:57 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +const CardWeather = () => {
This is a complex file (complex it's meaning prepared page for the route (app.tsx) with components inside). 

Please divide it to:
1. /src/components/complex/weather
2. /src/components/ui/weather-card

2022-10-05 12:58 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +    <CardStyled>
This is some kind of wrapper for the weather card. Please rename it. Maybe WeatherWrapper

2022-10-05 13:01 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +      </Card>
It will be in the complex file

2022-10-05 13:02 UTC, toserg commented on src/components/ui/weather-card/weather-card.styled.tsx
> +export const LayoutStyled = styled.div``;
Be attentive. Move it to the Layout folder

2022-10-05 13:08 UTC, toserg commented on src/hooks/card-weather-hook.tsx
> +const cardWeatherHook = () => {
not the correct hook name. Be attentive. All hook's names must start with useYourHookName (**use** at the start).
The file name is the same 'use-your-name.ts' (**use** at the start and **.ts** at the end)

2022-10-05 13:09 UTC, toserg commented on src/hooks/card-weather-hook.tsx
> +const cardWeatherHook = () => {
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! And like I say **4 times** MOVE THAT FUKING FILE to the weather card folder !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2022-10-05 13:21 UTC, VictorYarosh commented on src/components/containers/types.ts
> +// }
delet this

2022-10-05 13:21 UTC, VictorYarosh commented on src/components/ui/navbar/navbar.styled.tsx
> +  @media (max-width: 425px) {
+

2022-10-05 13:24 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +const CardWeather = () => {
done

2022-10-05 13:25 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +    <CardStyled>
done

2022-10-05 13:31 UTC, VictorYarosh commented on src/components/ui/weather-card/weather-card.styled.tsx
> +export const LayoutStyled = styled.div``;
done

2022-10-05 13:39 UTC, VictorYarosh commented on src/hooks/card-weather-hook.tsx
> +const cardWeatherHook = () => {
if i`m understend you, i fix

2022-10-05 20:00 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +      </Card>
FIX!!!

2022-10-05 20:01 UTC, toserg commented on src/components/ui/navbar/navbar.styled.tsx
> +  @media (max-width: 425px) {
NOT DONE! PLEASE FIX!

2022-10-05 20:01 UTC, toserg commented on src/components/containers/types.ts
> +// }
NOT DONE! PLEASE FIX!

2022-10-05 20:02 UTC, toserg commented on src/components/containers/layout.tsx
> +    <CardWeather />
NOT DONE! PLEASE FIX!

2022-10-05 20:02 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +      </Card>
NOT DONE! PLEASE FIX!

2022-10-05 20:02 UTC, toserg commented on src/components/ui/weather-card/weather-card.styled.tsx
> +export const LayoutStyled = styled.div``;
NOT DONE! PLEASE FIX!

2022-10-05 20:02 UTC, toserg commented on src/hooks/card-weather-hook.tsx
> +const cardWeatherHook = () => {
NOT DONE! PLEASE FIX!

2022-10-05 20:03 UTC, toserg requested changes
NOT DONE! PLEASE FIX!

2022-10-05 20:21 UTC, VictorYarosh commented on src/components/ui/navbar/navbar.styled.tsx
> +  @media (max-width: 425px) {
fix

2022-10-05 20:38 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +const CardWeather = () => {
Im fix name coplex weather.tsx and she has prepared page

2022-10-05 20:41 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +    <CardStyled>
this WeatherWrapper im use in weather

2022-10-05 20:50 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +      </Card>
Im rename but what are you talking about leave? im prepared in WeatherCard all logic and put in weather or do you still need to break it?

2022-10-05 20:53 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +      </Card>
I do not understand

2022-10-05 21:40 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +const CardWeather = () => {
You didn't fix the name. Now I see:
component name: **CardWeather**
file/folder name: **weather-card** 

You should rename the component to **WeatherCard**.

Please create a folder with the name component/complex/**weather**
Inside the folder, create a file with the name **index.tsx**

and create component:

name **Weather**

`<Weather>
        <WeatherCard/>
        <WeatherCardControl />
      </Weather>`

2022-10-05 21:45 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +      </Card>
this file weather-card/index.tsx - is just a simple standalone component, not a whole page!!!!!!
No need to use two cards inside. You need divide it, make simple WeatherCard component with one card. And after that add WeatherCard to complex/weather/index.tsx (this is major page).

example complex/weather/index.tsx file:
`<WeatherWrapper> <WeatherCard/> <WeatherCardControl /> </WeatherWrapper>`

2022-10-05 21:47 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +      </Card>
Move that lines to the new component **WeatherCardControl** and after that use it in the file 
 complex/weather/index.tsx

example how to use:
`<WeatherWrapper> <WeatherCard/> <WeatherCardControl /> </WeatherWrapper>`

2022-10-06 11:26 UTC, VictorYarosh commented on src/components/containers/layout.tsx
> +    <CardWeather />
took it out

2022-10-06 11:28 UTC, VictorYarosh commented on src/components/containers/types.ts
> +// }
I created a separate  layout.styled

2022-10-06 11:30 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +      </Card>
there is only this card

2022-10-06 11:32 UTC, VictorYarosh commented on src/components/ui/weather-card/weather-card.styled.tsx
> +export const LayoutStyled = styled.div``;
I created a separate style

2022-10-06 11:40 UTC, VictorYarosh commented on src/hooks/card-weather-hook.tsx
> +const cardWeatherHook = () => {
I renamed it and moved it to a folder weather-card.

2022-10-06 13:51 UTC, toserg commented on src/components/complex/main/weather.tsx
> +const Weather = () => {
`const Weather: FC () => {
`
Try to use the function component.
For that tag your components with **FC**

2022-10-06 13:58 UTC, toserg commented on src/components/complex/main/weather-wrapper.styled.tsx
> +`;
The file name is the same as the main component or folder name.

2022-10-06 16:14 UTC, VictorYarosh commented on src/components/complex/main/weather-wrapper.styled.tsx
> +`;
this rename

2022-10-06 16:49 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +  const { dateBuilder, data } = useWeatherHook();
fix

2022-10-06 18:54 UTC, VictorYarosh commented on src/index.css
>  code {
fix

2022-10-10 14:06 UTC, toserg commented on src/app.test.tsx
>    render(<App />);
You can remove it.

2022-10-10 14:07 UTC, toserg commented on src/app.tsx
> +            {<Weather />}
unnecessary brackets` {<Weather />} => <Weather />`

2022-10-10 14:10 UTC, toserg commented on src/components/ui/weather-card/index.tsx
> +          {' '}
Unnecessary brackets and space, remove it

2022-10-10 14:13 UTC, toserg requested changes
Fix comments

2022-10-10 15:58 UTC, VictorYarosh commented on src/app.tsx
> +            {<Weather />}
fix

2022-10-10 16:00 UTC, VictorYarosh commented on src/components/ui/weather-card/index.tsx
> +          {' '}
fix

2022-10-10 17:48 UTC, toserg approved these changes
Good job!

2022-10-10 17:50 UTC, merged